TRANSACTION_SHEET_TITLE = "2024 Transactions"
CATEGORY_SHEET_TITLE = "Categories"
GOOGLE_SHEET_ID = "1wnF2WVgfnDC9-oLQqXwkOjfWs66Yq3A5TNDafiD8c7M"
GOOGLE_API_CREDENTIALS_FILE = "import-finances-d4b7b2a81f11.json"