TRANSACTION_SHEET_TITLE = "Sheet2"#"2024 Transactions"
CATEGORY_SHEET_TITLE = "Categories"
GOOGLE_SHEET_ID = "1wnF2WVgfnDC9-oLQqXwkOjfWs66Yq3A5TNDafiD8c7M"
GOOGLE_API_CREDENTIALS_FILE = "import-finances-59ac45b427a9.json"